if (F)
   suppressMessages(require(highcharter))
if (T)
   suppressMessages(require(plotly))
require(ggplot2)
source("./resources.R")
source("./simulate.R")
source("./analyze.R")
source("./perturb.R")
isShiny <- ("shiny" %in% loadedNamespaces())
#isShiny <- (("shiny" %in% loadedNamespaces())&&(length(shiny::shinyOptions())>0))
init <- randomize(firstRun=isShiny)
options(stringsAsFactors=FALSE
       ,show.error.messages=TRUE
       ,warn=ifelse(isShiny,1,10)
       )
