#print(commandArgs(FALSE))
#print(c(pwd=getwd()))
if (F)
   suppressMessages(require(highcharter))
if (T)
   suppressMessages(require(plotly))
require(ggplot2)
local <- FALSE
source("./resources.R",local=local)
source("./simulate.R",local=local)
source("./analyze.R",local=local)
source("./perturb.R",local=local)
isShiny <- ("shiny" %in% loadedNamespaces())
isKnitr <- ("knitr" %in% loadedNamespaces())&&(is.character(knitr::current_input()))
#isShiny <- (("shiny" %in% loadedNamespaces())&&(length(shiny::shinyOptions())>0))
init <- randomize(firstRun=isShiny)
initRange <- rangePrm()
options(stringsAsFactors=FALSE
       ,show.error.messages=TRUE
       ,warn=ifelse(isShiny,1,10)
       )
