---
pagetitle: Polar Bear Demography
skipdate: "`r format(Sys.Date(),'%d %B, %Y')`"
thanks: оргкомитет
output:
   word_document: default
   html_vignette:
      css: C:/platt/R/style/html_vignette.css
---

```{r include=FALSE}
filetype <- knitr::opts_knit$get("rmarkdown.pandoc.to")
isHTML <- filetype %in% c("html4")
isDOCX <- filetype %in% c("docx")
```

**Разработка инструмента для оценки демографических особенностей белого медведя**

Платонов Н.Г., Иванов Е.А., Мордвинцев И.Н., Найденко С.В., Рожнов В.В.

*Институт проблем экологии и эволюции им. А.Н. Северцова Российской Академии наук, Москва*

Построена имитационная модель оценки демографических показателей белого медведя (*Ursus maritimus*). На каждом шаге изменение половозрастного состава населения (с явными связями матерей и детенышей) моделируемой популяции происходит под влиянием заданных демографических показателей. Применяются следующие особенности: временной шаг один год, отчет ведется с момента выхода медвежат из берлоги; размер выводка от 1 до 3 медвежат; закон смертности Гомперца-Мейкхама; возрастная зависимость фертильности самок; семьи могут распадаться в возрасте медвежат как 1 года, так и 2 лет; выживаемость молодняка различна для детенышей внутри и вне семейной группы. Используется целочисленное исчисление и рандомизированный выбор.

Инструмент позволяет выявить обобщенные особенности демографии белого медведя. В среднем, самки приносят потомство каждые 2-3 года в зависимости от того, как долго детеныши остаются со своими матерями. В течение жизни у половины самок рождение детенышей случается 3-4 раза и реже; долгоживущие самки могут выводить потомство до 11-12 раз. Чаще всего появление потомства происходит 1-2 раза за жизнь, и частота каждой последующей беременности уменьшается. Из всего потомства, выращенного самкой за всю жизнь, до возраста 3 лет и старше доживают, в среднем, два детеныша и меньше.

Соответствующие действительности исходные данные позволяют извлечь дополнительные демографические характеристики. Для примера рассмотрены усредненные значения размера выводка сеголеток (1.7) и темпа воспроизводства сеголеток (0.35) и годовалых медвежат (0.13) по данным Мониторинга окружающей среды Шпицбергена (MOSJ) для западной части баренцевоморской популяции. Для достижения этих показателей подобраны наборы подходящих демографических характеристик. В целом, вероятность успеха размножения самки составила около 0.6, и примерно 45% самок перестают водить медвежат до достижения двухлетнего возраста.

Репозиторий проекта https://github.com/nplatonov/demography.

**Development of the service for evaluation of polar bear demography features**

Platonov N.G., Ivanov E.A., Mordvintsev I.N., Naidenko S.V., Rozhnov V.V.

*A.N. Severtsov Institute of Ecology and Evolution, Russian Academy of Sciences, Moscow*

The dynamical simulation for evaluation of polar bear (*Ursus maritimus*) demography has been developed. On each stage, the change of age and sexual structure (with explicit mother-cub relations) of modelled subpopulation is forced by specified demographical parameters. The followed approaches and statements are considered: temporal resolution is one year, time of census is period of cubs emergence; litter size is 1 to 3 cubs; Gompertz–Makeham law of mortality is involved; the female fertility is age-specific; mothers leave their cubs in both ages of 1 and 2, and age-specific survival rates for dependent and independent cubs is different. All selections are random, and calculations are integer.

This service allows extracting generalized features of polar bear demography. On the average, interbirth (mating) interval is 2-3 years; it depends how long cubs remain with their mothers. A half of females gives birth to 3-4 litters or less during their lifespan; the long-lived females can produce 11-12 litters or less. The single and double births are most frequent, and frequency of each subsequent appearance of cubs falls. In general, among all cubs having a birth from one female during her lifespan only two ones or less reach the age 3 or older.

Relevant data inputs expand set of extracted demographical features. For example, averaged estimates of litter size (1.7, cubs of ther year), litter production rate of cubs of the year (0.35) and yearlings (0.13) for polar bears in the western part of the Barents Sea from Environmental monitoring of Svalbard and Jan Mayen (MOSJ) were defined as target indicators. Several sets of demographical parameters for which these indicators are achieved were selected. Generally, the birth success is near 0.6, and around 45% of females wean cubs before age of two.

Project is hosted on https://github.com/nplatonov/demography.

