---
pagetitle: Polar Bear Demography
title: Моделирование демографических показателей белого медведя
author:
   - name: Платонов Н.Г.
     affiliation: ИПЭЭ РАН
   - name: Иванов Е.А.
     affiliation: ИПЭЭ РАН
   - name: Мордвинцев И.Н.
     affiliation: ИПЭЭ РАН
   - name: Найденко С.В.
     affiliation: ИПЭЭ РАН
   - name: Рожнов В.В.
     affiliation: ИПЭЭ РАН
skipdate: "`r format(Sys.Date(),'%d %B, %Y')`"
thanks: оргкомитет
output:
   word_document: default
   html_vignette:
      css: C:/platt/R/style/html_vignette.css
---

```{r include=FALSE}
filetype <- knitr::opts_knit$get("rmarkdown.pandoc.to")
isHTML <- filetype %in% c("html4")
isDOCX <- filetype %in% c("docx")
```

`r if (isDOCX)
      paste("Платонов Н.Г., Иванов Е.А., Мордвинцев И.Н., Найденко С.В., Рожнов В.В."
           ,"","*ИПЭЭ РАН*",sep="\n")`

Построена имитационная модель оценки демографических показателей белого медведя (*Ursus maritimus*). Основу модели составляют оценки числа родовых берлог для популяции (группировки) и удельная выживаемость одногодков. Временной шаг составляет один год, отчет ведется с момента выхода медвежат из берлоги. 

Принимается во внимание размер выводка от 1 до 3 медвежат первого года жизни, учитывается закон смертности Гомперца-Мейкхама, используется возрастная зависимость фертильности самок, рассматривается частота разрушения семей после одного и двух лет и различная выживаемость молодняка внутри и вне семейной группы, предполагается отсутствие беременности после гонного периода для части самок, применяется целочисленное исчисление в рандомизированных процедурах.

Проект находится в стадии развития, пока не получено результатов для конкретных популяций, однако можно извлечь некоторые демографические особенности жизни белого медведя в целом.

В среднем, рожавшие самки приносят потомство каждые 2-3 года, при этом большую роль играют случаи оставления потомства в годовалом возрасте. Репродуктивный цикл в 2 года не является индикатором отрицательного прироста численности; стабильность может достигнута за счет высоких значений других демографических показателей.

В течение продолжительности жизни самки могут выводить потомство до 11-12 раз, половина успешно залегает в родовые берлоги 3-4 раза и реже. Однократная и двукратная беременности встречаются чаще всего, и вероятность каждой последующей беременности уменьшается.

Из всего потомства, выращенного самкой за всю жизнь, до возраста взрослой особи доживают, в среднем, два детеныша и меньше.

<!--
Одним из индикаторов сокращения численности популяции, который может быть оценен в ходе проведения полевых работ, может служить высокая доля молодых самок с сеголетками.
-->


<!--
При оценке численности популяции по числу родовых берлог важно принимать во внимание размер выводка медвежат первого года.
-->

Репозиторий проекта https://github.com/nplatonov/demography.
